name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.ponypressx.com", custom_domain = true },
#   { pattern = "quay.ponypressx.com", custom_domain = true },
#   { pattern = "gcr.ponypressx.com", custom_domain = true },
#   { pattern = "k8s-gcr.ponypressx.com", custom_domain = true },
#   { pattern = "k8s.ponypressx.com", custom_domain = true },
#   { pattern = "ghcr.ponypressx.com", custom_domain = true },
#   { pattern = "cloudsmith.ponypressx.com", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.ponypressx.com", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""

# wrangler.toml (wrangler v3.78.6^)
[observability]
enabled = true
